import "./globals.css";
import localFont from "next/font/local";
import { ServiceWorkerRegister } from "@/lib/serviceWorkerRegister";

import Head from "next/head";
export const dynamic = "force-dynamic";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Rupeia",
  description: "Generated by Rupeia",
  generator: "Next.js",
  manifest: "/manifest.json",
  link: [
    {
      rel: "stylesheet",
      href: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Raleway:wght@400;600&family=Roboto:wght@400;600&display=swap",
    },
  ],
  icons: {
    icon: "/favicon.ico", // put favicon.ico in public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* ✅ Add the manifest file link */}
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ServiceWorkerRegister />
        {children}
      </body>
    </html>
  );
}
